# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  # api section
  catalogapi:
    container_name: catalogapi
    image: catalogapi
    ports:
      - 6000:8080
      - 6060:8081
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
      args:
        - configuration=Debug
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passw0rd123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalogdb
    volumes:
      - ./certs:/https/
  basketapi:
    container_name: basketapi
    image: basketapi
    ports:
      - 6001:8080
      - 6061:8081
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
      args:
        - configuration=Debug
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discountrpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passw0rd123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - basketdb
      - distributedcache
      - discountrpc
      - messagebroker
    volumes:
      - ./certs:/https/
  orderingapi:
    container_name: orderingapi
    image: orderingapi
    ports:
      - 6003:8080
      - 6063:8081
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
      args:
        - configuration=Debug
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFulfillment=false
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passw0rd123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - orderdb
      - messagebroker
    volumes:
      - ./certs:/https/      
  # database section
  catalogdb:
    image: postgres:latest
    container_name: catalogdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "6432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    image: postgres:latest
    container_name: basketdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - "6433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
      
  orderdb:
    image: mcr.microsoft.com/mssql/server
    restart: on-failure
    container_name: orderdb
    hostname: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
      - platform=linux/amd64
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SwN12345678 -Q "select 1"
      interval: 30s
      timeout: 30s
      retries: 3
    platform: linux/amd64
    ports:
      - "1433:1433"
  #others section
  messagebroker:
    container_name: messagebroker
    image: rabbitmq:management
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    
  distributedcache:
    container_name: distributedcache
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  discountrpc:
    container_name: discountrpc
    image: discountrpc
    ports:
      - 6002:8080
      - 6062:8081
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile
      args:
        - configuration=Debug
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb/discount.db
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passw0rd123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Endpoints__GrpcHttp__Url=http://0.0.0.0:8080
      - Kestrel__Endpoints__GrpcHttp__Protocols=Http2
      - Kestrel__Endpoints__GrpcHttps__Url=https://0.0.0.0:8081
      - Kestrel__Endpoints__GrpcHttps__Protocols=Http2

    volumes:
      - ./certs:/https/
      - ./discount.db:/app/discountdb

volumes:
  postgres_catalog:
  postgres_basket:

